# Generated by Django 5.1 on 2024-08-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Category"},
        ),
    ]
