# Generated by Django 5.1 on 2024-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_api", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "FOOD"),
                    ("TRANSPORTATION", "TRANSPORTATION"),
                    ("HOUSING", "HOUSING"),
                    ("INSURANCE", "INSURANCE"),
                    ("DEBT", "DEBT"),
                    ("ENTERTAINMENT", "ENTERTAINMENT"),
                    ("CLOTHING", "CLOTHING"),
                    ("HEALTH_AND_WELLNESS", "HEALTH_AND_WELLNESS"),
                    ("PERSONAL_CARE", "Personal Care"),
                    ("EDUCATION", "EDUCATION"),
                    ("GIFTS", "GIFTS"),
                    ("ONLINE_SERVICES", "ONLINE_SERVICES"),
                    ("OTHERS", "OTHERS"),
                ],
                default="FOOD",
                max_length=200,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
