# Generated by Django 5.1 on 2024-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_api", "0007_alter_income_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.CharField(
                choices=[
                    ("SALARY", "SALARY"),
                    ("BUSINESS", "BUSINESS"),
                    ("SIDE_HUSTLE", "SIDE_HUSTLE"),
                    ("INVESTMENTS", "INVESTMENTS"),
                    ("INHERITANCE", "INHERITANCE"),
                    ("GIFTS", "GIFTS"),
                    ("OTHERS", "OTHERS"),
                ],
                default="SALARY",
                max_length=150,
            ),
        ),
    ]
