# Generated by Django 5.1 on 2024-08-26 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_api", "0009_alter_expense_options_alter_income_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="month",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
