# Generated by Django 5.1 on 2024-09-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_api", "0010_alter_budget_month_alter_expense_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "FOOD"),
                    ("TRANSPORTATION", "TRANSPORTATION"),
                    ("HOUSING", "HOUSING"),
                    ("INSURANCE", "INSURANCE"),
                    ("DEBT", "DEBT"),
                    ("ENTERTAINMENT", "ENTERTAINMENT"),
                    ("CLOTHING", "CLOTHING"),
                    ("HEALTH AND WELLNESS", "HEALTH AND WELLNESS"),
                    ("PERSONAL CARE", "PERSONAL CARE"),
                    ("EDUCATION", "EDUCATION"),
                    ("GIFTS", "GIFTS"),
                    ("ONLINE SERVICES", "ONLINE SERVICES"),
                    ("OTHERS", "OTHERS"),
                ],
                default="FOOD",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.CharField(
                choices=[
                    ("SALARY", "SALARY"),
                    ("BUSINESS", "BUSINESS"),
                    ("SIDE HUSTLE", "SIDE HUSTLE"),
                    ("INVESTMENTS", "INVESTMENTS"),
                    ("INHERITANCE", "INHERITANCE"),
                    ("GIFTS", "GIFTS"),
                    ("OTHERS", "OTHERS"),
                ],
                default="SALARY",
                max_length=150,
            ),
        ),
    ]
