# Generated by Django 5.1 on 2024-09-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_api", "0011_alter_expense_category_alter_income_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
