# Generated by Django 5.1 on 2024-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense_api", "0012_budget_description_alter_expense_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"verbose_name_plural": "Budget"},
        ),
    ]
